### ISSUE TITLE
Android 9 version not recognized

### ISSUE THREAD

**Issue by vincentdaniel** [woothee/woothee-java#18]
We noticed that the version of user agents for Android 9 wasn't parsed properly by Woothee. This because the user agent contains `Android 9` and not `Android 9.0`.

For example, the version for the following user agent would be `null` instead of `9`: `Mozilla/5.0 (Linux; Android 9; SM-N960F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.105 Mobile Safari/537.36`

We tested it with our own phones so we are sure that these are valid user agents for Android 9 devices (and not some fake user agents :) )

([A similar PR](https://github.com/woothee/woothee-ruby/pull/18) is open in the Ruby version of Woothee)

**Comment by tagomoris** [comment]
@vincentdaniel Thank you for reporting it!
Could you send a pull-request to the spec about UA strings and these parse results in [spec repository](https://github.com/woothee/woothee)? All implementations will follow it with new version numbers.

**Comment by vincentdaniel** [comment]
Sure, I will do that
