### ISSUE TITLE
Issues generating jar file(with hive UDF)

### ISSUE THREAD

**Issue by nitinkak001** [woothee/woothee-java#3]
I am getting this error while generating the jar using these two steps.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project woothee-java: Compilation failure
[ERROR] /home/kakn01/wootheejar-test/woothee-java-master/src/main/java/is/tagomor/woothee/DataSet.java:[43,106] reached end of file while parsing
[ERROR] -> [Help 1]

1. Install git, JDK and Maven
2. Do mvn -P hiveudf with two -D options for hadoop-version and hive-version
mvn package -P hiveudf -Dhadoop-version=0.23.11 -Dhive-version=0.13.0

I am assuming there is another step before the above two steps: download the source code from master, then run the "mvn" command from the root directory of the extracted source. We need a pom.xml file to run the mvn command right? Please let me know if I am wrong.

**Comment by tagomoris** [comment]
Did you use woothee-java-1.0.0.tar.gz?
Please clone this repository and use it. I'd not released tarball of latest version with latest build configuration files yet.

**Comment by tagomoris** [comment]
Now there is 1.0.1 tarball in releases page. It includes pom.xml and all others to build with maven.
Please reopen if you still in trouble.
